INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES 
('sdft_meatfree', 'Meat Free Burger', 1, 0, 1),
('sdft_heartstopper', 'Heartstopper Burger', 1, 0, 1),
('sdft_bleeder', 'Bleeder Burger', 1, 0, 1),
('sdft_moneyshot', 'Moneyshot Burger', 1, 0, 1),
('sdft_torpedo', 'Torpedo Burger', 1, 0, 1),
('sdft_fries', 'Fries', 1, 0, 1),
('sdft_milkshake', 'Milkshake', 1, 0, 1),

('sdft_hotdog', 'Hotdog', 1, 0, 1),
('sdft_sausagedog', 'Sausage Dog', 1, 0, 1),
('sdft_pretzel', 'Pretzel', 1, 0, 1),
('sdft_minipretzels', 'Mini Pretzels', 1, 0, 1),
('sdft_roastednuts', 'Roasted Nuts', 1, 0, 1),

('sdft_burger', 'Burger', 1, 0, 1),
('sdft_megacheese', 'Megacheese Burger', 1, 0, 1),
('sdft_doubleburger', 'Double Burger', 1, 0, 1),
('sdft_kingsizeburger', 'King Size Burger', 1, 0, 1),
('sdft_baconburger', 'Bacon Burger', 1, 0, 1),

('sdft_pizzaslice', 'Pizza Slice', 1, 0, 1),
('sdft_donut', 'Donut', 1, 0, 1),
('sdft_smoothie', 'Smoothie', 1, 0, 1),

('sdft_taco_carneasada', 'Carne Asada Taco', 1, 0, 1),
('sdft_taco_elpastor', 'El Pastor Taco', 1, 0, 1),
('sdft_burrito_carneasada', 'Carne Asada Burrito', 1, 0, 1),
('sdft_burrito_elpastor', 'El Pastor Burrito', 1, 0, 1),
('sdft_torta_carneasada', 'Carne Asada Torta', 1, 0, 1),
('sdft_torta_elpastor', 'El Pastor Torta', 1, 0, 1),
('sdft_quesadilla', 'Quesadilla', 1, 0, 1),
('sdft_tostada', 'Tostada', 1, 0, 1),

('sdft_lettuce', 'Lettuce', 1, 0, 1),
('sdft_cheese', 'Cheese Slice', 1, 0, 1),
('sdft_tomato', 'Tomato', 1, 0, 1),
('sdft_patty', 'Raw Patty', 1, 0, 1),
('sdft_patty_cooked', 'Cooked Patty', 1, 0, 1),
('sdft_vpatty', 'Veggie Patty', 1, 0, 1),
('sdft_vpatty_cooked', 'Cooked Veggie Patty', 1, 0, 1),
('sdft_rawfries', 'Raw Fries', 1, 0, 1),
('sdft_fries_cooked', 'Cooked Fries', 1, 0, 1),
('sdft_bun', 'Burger Bun', 1, 0, 1),
('sdft_bun_cooked', 'Toasted Bun', 1, 0, 1),
('sdft_hoagie', 'Hoagie', 1, 0, 1),
('sdft_hoagie_cooked', 'Toasted Hoagie', 1, 0, 1),
('sdft_cheesesauce', 'Cheese Sauce', 1, 0, 1),
('sdft_dog', 'Raw Dog', 1, 0, 1),
('sdft_dog_cooked', 'Cooked Dog', 1, 0, 1),
('sdft_sausage', 'Sausage', 1, 0, 1),
('sdft_sausage_cooked', 'Cooked Sausage', 1, 0, 1),
('sdft_rawpretzel', 'Raw Pretzel Dough', 1, 0, 1),
('sdft_pretzel_cooked', 'Cooked Pretzel', 1, 0, 1),
('sdft_minipretzel', 'Mini Pretzels', 1, 0, 1),
('sdft_minipretzel_cooked', 'Cooked Mini Pretzels', 1, 0, 1),
('sdft_nuts', 'Nuts', 1, 0, 1),
('sdft_nuts_cooked', 'Roasted Nuts', 1, 0, 1),
('sdft_hotdogbun', 'Hotdog Bun', 1, 0, 1),
('sdft_hotdogbun_cooked', 'Toasted Hotdog Bun', 1, 0, 1),
('sdft_bacon', 'Raw Bacon', 1, 0, 1),
('sdft_bacon_cooked', 'Cooked Bacon', 1, 0, 1),
('sdft_pizza', 'Frozen Pizza', 1, 0, 1),
('sdft_pizza_cooked', 'Cooked Pizza', 1, 0, 1),
('sdft_rawdonut', 'Donut Dough', 1, 0, 1),
('sdft_donut_cooked', 'Donut', 1, 0, 1),
('sdft_shreddedcheese', 'Shredded Cheese', 1, 0, 1),
('sdft_carneasada', 'Raw Carne Asada', 1, 0, 1),
('sdft_carneasada_cooked', 'Cooked Carne Asada', 1, 0, 1),
('sdft_elpastor', 'Raw El Pastor', 1, 0, 1),
('sdft_elpastor_cooked', 'Cooked El Pastor', 1, 0, 1),
('sdft_torilla', 'Tortilla', 1, 0, 1)

--If you need these you can add them too
--('water_bottle', 'Water bottle', 1, 0, 1),
--('sprunk', 'Sprunk', 1, 0, 1),
--('ecola', 'eCola', 1, 0, 1),
;

