-- Put these items to your ox_inventory/data/items.lua


------------------------------SDC_Moonshine Items------------------------------
['sdam_ebarrel'] = {
    label = 'Empty Barrel',
    weight = 100,
    stack = true,
    close = true,
    description = 'Place Down This Barrel To Start Fermenting A Mash!',
},
['sdam_ejug'] = {
    label = 'Empty Jug',
    weight = 100,
    stack = true,
    close = true,
    description = 'Use This When Making Moonshine!',
},
['sdam_stillpart1'] = {
    label = 'Main Still Part',
    weight = 500,
    stack = true,
    close = true,
    description = 'Use To Create A Still!',
},
['sdam_stillpart2'] = {
    label = 'Still Part 2',
    weight = 500,
    stack = true,
    close = true,
    description = 'Use To Create A Still!',
},
['sdam_stillpart3'] = {
    label = 'Still Part 3',
    weight = 500,
    stack = true,
    close = true,
    description = 'Use To Create A Still!',
},
['sdam_coil'] = {
    label = 'Copper Coil',
    weight = 10,
    stack = true,
    close = true,
    description = 'Use To Create A Still!',
},
['sdam_watergallon'] = {
    label = 'Gallon of Water',
    weight = 10,
    stack = true,
    close = true,
    description = 'Used When Making Moonshine!',
},
['sdam_firewood'] = {
    label = 'Firewood',
    weight = 10,
    stack = true,
    close = true,
    description = 'Used To Fuel A Moonshine Still!',
},
['sdam_bagofcorn'] = {
    label = 'Bag Of Corn',
    weight = 100,
    stack = true,
    close = true,
    description = 'Used To Make Mash!',
},
['sdam_bagofsugar'] = {
    label = 'Bag Of Sugar',
    weight = 100,
    stack = true,
    close = true,
    description = 'Used To Make Mash!',
},
['sdam_bagofyeast'] = {
    label = 'Bag Of Yeast',
    weight = 100,
    stack = true,
    close = true,
    description = 'Used To Make Mash!',
},
['sdam_apple'] = {
    label = 'Apple',
    weight = 1,
    stack = true,
    close = true,
    description = 'Used To Make A Mash!',
},
['sdam_pear'] = {
    label = 'Pear',
    weight = 1,
    stack = true,
    close = true,
    description = 'Used To Make A Mash!',
},
['sdam_peach'] = {
    label = 'Peach',
    weight = 1,
    stack = true,
    close = true,
    description = 'Used To Make A Mash!',
},
['sdam_cherries'] = {
    label = 'Cherries',
    weight = 1,
    stack = true,
    close = true,
    description = 'Used To Make A Mash!',
},
['sdam_plum'] = {
    label = 'Plum',
    weight = 1,
    stack = true,
    close = true,
    description = 'Used To Make A Mash!',
},
['sdam_banana'] = {
    label = 'Banana',
    weight = 1,
    stack = true,
    close = true,
    description = 'Used To Make A Mash!',
},
['sdam_apricot'] = {
    label = 'Apricot',
    weight = 1,
    stack = true,
    close = true,
    description = 'Used To Make A Mash!',
},
['sdam_mango'] = {
    label = 'Mango',
    weight = 1,
    stack = true,
    close = true,
    description = 'Used To Make A Mash!',
},
['sdam_strawberry'] = {
    label = 'Strawberry',
    weight = 1,
    stack = true,
    close = true,
    description = 'Used To Make A Mash!',
},
['sdam_blueberry'] = {
    label = 'Blueberry',
    weight = 1,
    stack = true,
    close = true,
    description = 'Used To Make A Mash!',
},
['sdam_grape'] = {
    label = 'Grape',
    weight = 1,
    stack = true,
    close = true,
    description = 'Used To Make A Mash!',
},
['sdam_pineapple'] = {
    label = 'Pineapple',
    weight = 1,
    stack = true,
    close = true,
    description = 'Used To Make A Mash!',
},
['sdam_orange'] = {
    label = 'Orange',
    weight = 1,
    stack = true,
    close = true,
    description = 'Used To Make A Mash!',
},
['sdam_raspberry'] = {
    label = 'Raspberry',
    weight = 1,
    stack = true,
    close = true,
    description = 'Used To Make A Mash!',
},
['sdam_blackberry'] = {
    label = 'Blackberry',
    weight = 1,
    stack = true,
    close = true,
    description = 'Used To Make A Mash!',
},
['sdam_kiwi'] = {
    label = 'Kiwi',
    weight = 1,
    stack = true,
    close = true,
    description = 'Used To Make A Mash!',
},
['sdam_shine_apple'] = {
    label = 'Apple Pie Moonshine',
    weight = 10,
    stack = true,
    close = true,
    description = 'Some Yummy Moonshine!',
},
['sdam_shine_pear'] = {
    label = 'Pear Moonshine',
    weight = 10,
    stack = true,
    close = true,
    description = 'Some Yummy Moonshine!',
},
['sdam_shine_peach'] = {
    label = 'Peach Moonshine',
    weight = 10,
    stack = true,
    close = true,
    description = 'Some Yummy Moonshine!',
},
['sdam_shine_cherries'] = {
    label = 'Cherry Moonshine',
    weight = 10,
    stack = true,
    close = true,
    description = 'Some Yummy Moonshine!',
},
['sdam_shine_plum'] = {
    label = 'Plum Moonshine',
    weight = 10,
    stack = true,
    close = true,
    description = 'Some Yummy Moonshine!',
},
['sdam_shine_banana'] = {
    label = 'Banana Split Moonshine',
    weight = 10,
    stack = true,
    close = true,
    description = 'Some Yummy Moonshine!',
},
['sdam_shine_apricot'] = {
    label = 'Apricot Moonshine',
    weight = 10,
    stack = true,
    close = true,
    description = 'Some Yummy Moonshine!',
},
['sdam_shine_mango'] = {
    label = 'Mango Moonshine',
    weight = 10,
    stack = true,
    close = true,
    description = 'Some Yummy Moonshine!',
},
['sdam_shine_strawberry'] = {
    label = 'Strawberry Moonshine',
    weight = 10,
    stack = true,
    close = true,
    description = 'Some Yummy Moonshine!',
},
['sdam_shine_blueberry'] = {
    label = 'Blueberry Moonshine',
    weight = 10,
    stack = true,
    close = true,
    description = 'Some Yummy Moonshine!',
},
['sdam_shine_grape'] = {
    label = 'Grape Moonshine',
    weight = 10,
    stack = true,
    close = true,
    description = 'Some Yummy Moonshine!',
},
['sdam_shine_pineapple'] = {
    label = 'Pineapple Moonshine',
    weight = 10,
    stack = true,
    close = true,
    description = 'Some Yummy Moonshine!',
},
['sdam_shine_orange'] = {
    label = 'Orange Moonshine',
    weight = 10,
    stack = true,
    close = true,
    description = 'Some Yummy Moonshine!',
},
['sdam_shine_raspberry'] = {
    label = 'Raspberry Moonshine',
    weight = 10,
    stack = true,
    close = true,
    description = 'Some Yummy Moonshine!',
},
['sdam_shine_blackberry'] = {
    label = 'Blackberry Moonshine',
    weight = 10,
    stack = true,
    close = true,
    description = 'Some Yummy Moonshine!',
},
['sdam_shine_kiwi'] = {
    label = 'Kiwi Moonshine',
    weight = 10,
    stack = true,
    close = true,
    description = 'Some Yummy Moonshine!',
},
------------------------------SDC_Moonshine Items------------------------------