INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES 
('sdam_ebarrel', 'Empty Barrel', 5, 0, 1),
('sdam_ejug', 'Empty Jug', 5, 0, 1),
('sdam_stillpart1', 'Main Still Part', 15, 0, 1),
('sdam_stillpart2', 'Still Part 2', 15, 0, 1),
('sdam_stillpart3', 'Still Part 3', 15, 0, 1),
('sdam_coil', 'Copper Coil', 1, 0, 1),

('sdam_watergallon', 'Gallon Of Water', 1, 0, 1),
('sdam_firewood', 'Firewood', 1, 0, 1),
('sdam_bagofcorn', 'Bag Of Corn', 5, 0, 1),
('sdam_bagofsugar', 'Bag Of Sugar', 5, 0, 1),
('sdam_bagofyeast', 'Bag Of Yeast', 5, 0, 1),

('sdam_apple', 'Apple', 1, 0, 1),
('sdam_pear', 'Pear', 1, 0, 1),
('sdam_peach', 'Peach', 1, 0, 1),
('sdam_cherries', 'Cherries', 1, 0, 1),
('sdam_plum', 'Plum', 1, 0, 1),
('sdam_banana', 'Banana', 1, 0, 1),
('sdam_apricot', 'Apricot', 1, 0, 1),
('sdam_mango', 'Mango', 1, 0, 1),
('sdam_strawberry', 'Strawberry', 1, 0, 1),
('sdam_blueberry', 'Blueberry', 1, 0, 1),
('sdam_pineapple', 'Pineapple', 1, 0, 1),
('sdam_orange', 'Orange', 1, 0, 1),
('sdam_raspberry', 'Raspberry', 1, 0, 1),
('sdam_blackberry', 'Blackberry', 1, 0, 1),
('sdam_kiwi', 'Kiwi', 1, 0, 1),

('sdam_shine_apple', 'Apple Pie Moonshine', 1, 0, 1),
('sdam_shine_pear', 'Pear Moonshine', 1, 0, 1),
('sdam_shine_peach', 'Peach Moonshine', 1, 0, 1),
('sdam_shine_cherries', 'Cherry Moonshine', 1, 0, 1),
('sdam_shine_plum', 'Plum Moonshine', 1, 0, 1),
('sdam_shine_banana', 'Banana Split Moonshine', 1, 0, 1),
('sdam_shine_apricot', 'Apricot Moonshine', 1, 0, 1),
('sdam_shine_mango', 'Mango Moonshine', 1, 0, 1),
('sdam_shine_strawberry', 'Strawberry Moonshine', 1, 0, 1),
('sdam_shine_blueberry', 'Blueberry Moonshine', 1, 0, 1),
('sdam_shine_pineapple', 'Pineapple Moonshine', 1, 0, 1),
('sdam_shine_orange', 'Orange Moonshine', 1, 0, 1),
('sdam_shine_raspberry', 'Raspberry Moonshine', 1, 0, 1),
('sdam_shine_blackberry', 'Blackberry Moonshine', 1, 0, 1),
('sdam_shine_kiwi', 'Kiwi Moonshine', 1, 0, 1)
;

