--Add this code below to ConsumeablesDrink in qb-smallresources/config.lua
["sdam_shine_apple"] = math.random(30, 40),
["sdam_shine_pear"] = math.random(30, 40),
["sdam_shine_peach"] = math.random(30, 40),
["sdam_shine_cherries"] = math.random(30, 40),
["sdam_shine_plum"] = math.random(30, 40),
["sdam_shine_banana"] = math.random(30, 40),
["sdam_shine_apricot"] = math.random(30, 40),
["sdam_shine_mango"] = math.random(30, 40),
["sdam_shine_strawberry"] = math.random(30, 40),
["sdam_shine_blueberry"] = math.random(30, 40),
["sdam_shine_grape"] = math.random(30, 40),
["sdam_shine_pineapple"] = math.random(30, 40),
["sdam_shine_orange"] = math.random(30, 40),
["sdam_shine_raspberry"] = math.random(30, 40),
["sdam_shine_blackberry"] = math.random(30, 40),
["sdam_shine_kiwi"] = math.random(30, 40),